_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 63
                - 74
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 63
                - 74
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.8.10
            "5": 0.19.1
            "6": 4.46.3
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
actuator_config:
    value:
        actuator_network_dir: null
        future_len: null
        history_len: null
        prediction_len: null
camera_names:
    value:
        - cam_high
        - cam_left_wrist
        - cam_right_wrist
ckpt_dir:
    value: /home/robot/Dataset_and_Checkpoint/checkpoint/act_plus_plus/test
episode_len:
    value: 600
eval_every:
    value: 2000
load_pretrain:
    value: false
lr:
    value: 1e-05
num_selected:
    value: 50
num_steps:
    value: 100000
onscreen_render:
    value: false
policy_class:
    value: SonicACT
policy_config:
    value:
        action_dim: 16
        backbone: resnet18
        camera_names:
            - cam_high
            - cam_left_wrist
            - cam_right_wrist
        dec_layers: 7
        dim_feedforward: 3200
        enc_layers: 4
        hidden_dim: 512
        kl_weight: 10
        lr: 1e-05
        lr_backbone: 1e-05
        nheads: 8
        no_encoder: false
        num_queries: 100
        vq: false
        vq_class: null
        vq_dim: null
real_robot:
    value: true
resume_ckpt_path:
    value: null
save_every:
    value: 2000
seed:
    value: 0
state_dim:
    value: 14
task_name:
    value: test
temporal_ensemble:
    value: false
validate_every:
    value: 2000
